/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qasystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.lang.reflect.Array;
import java.net.URL;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.util.Scanner;
import javax.lang.model.util.Elements;
import javax.swing.text.Element;
import org.jsoup.Jsoup;


/**
 *
 * @author utk
 */


            


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        answer = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Question Answer System");

        jLabel2.setText("Type your query: ");

        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel3.setText("Answer:");

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question)
                            .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submit)
                                .addGap(18, 18, 18)
                                .addComponent(Clear)
                                .addGap(18, 18, 18)
                                .addComponent(Exit)
                                .addGap(0, 85, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(Clear)
                    .addComponent(Exit)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
question.setText("");
answer.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

//Question Validation

String s=question.getText();
if(s.contains("who"))
s=s.substring(4);
else
if(s.contains("what"))
s=s.substring(5);
else
if(s.contains("where"))
s=s.substring(6);
else
if(s.contains("which"))
s=s.substring(6);
else
if(s.contains("why"))
s=s.substring(4);
else
if(s.contains("when"))
s=s.substring(5);
else
System.out.println("Not a valid question.");
System.out.println(s);
int len=s.length();

String []sub=s.split(" ");
for(int i=0;i<sub.length;i++) 
{
     System.out.println(sub[i]);
}


//Crawler

String google = "http://www.google.com/search?q=";
String search = s;
String charset = "UTF-8";
String userAgent = "ExampleBot 1.0 (+http://example.com/bot)"; // Change this to your company's name and bot homepage!
try
{
org.jsoup.select.Elements links = Jsoup.connect(google + URLEncoder.encode(search, charset)).userAgent(userAgent).get().select(".g>.r>a");

for (org.jsoup.nodes.Element link : links) {
    String title = link.text();
    String url = link.absUrl("href"); // Google returns URLs in format "http://www.google.com/url?q=<url>&sa=U&ei=<someKey>".
    url = URLDecoder.decode(url.substring(url.indexOf('=') + 1, url.indexOf('&')), "UTF-8");

    if (!url.startsWith("http")) {
        continue; // Ads/news/etc.
    }

      System.out.println("URL: " + url);
      try
        {
            URL website = new URL(url);
            ReadableByteChannel rbc = Channels.newChannel(website.openStream());
            
            FileOutputStream fos = new FileOutputStream("temp.html");
            
           
            fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
        }
        catch(Exception e)
        {}       

String content = "";
    try {
        BufferedReader in = new BufferedReader(new FileReader("temp.html"));
        String str;
        while ((str = in.readLine()) != null) {
            content +=str;
        }
        in.close();
    } catch (IOException e) {
    }
        
        String plaintext = Jsoup.parse(content).text();
int w;

BufferedWriter writer = null;
try
{   File file =new File("temp.txt");
    FileWriter fileWritter = new FileWriter(file.getName(),true);
     BufferedWriter bufferWritter = new BufferedWriter(fileWritter);
    
    for(w=0;w<plaintext.length();w++)
{
    if(plaintext.charAt(w)=='.')
    {
    bufferWritter.write(plaintext.charAt(w)+"\r\n");
    
    }
    else
    bufferWritter.write(plaintext.charAt(w));
    
}
}
catch ( IOException e)
{
}
      
      
      
}
}
catch(Exception e)
{}  
 



//Sentential Level Ranking 

File file = new File("temp.txt");


int u=0;
int i=0;

// WHATS THE USE OF THIS PART (INCLUDING A TEXT FILE??)??? -UTK

try {   // { ends @ 428
    
    Scanner scanner = new Scanner(file);

    int lineNum = 0;
   
    sentence[] x=new sentence[100];
    while (scanner.hasNextLine()) 
    
    {
        String line = scanner.nextLine();
       
        lineNum++;
        
               
        int z=0;
        int t=0;
        u=0;
for(z=0;z<sub.length;z++)
{
        
        if(line.contains(sub[z]))
        {   
        t=1;
        
        }
        else
        {
         t=0;
         
         break;
        }
}

if(t==1)         
{      
             if(i==0)
             {
              x[i]=new sentence();
              x[i].inputString(line);
              x[i].incRank();
              i++;
              
             }
             
             else
             {
                
             for(int n=0;n<i;n++)
            {
            if(line.equals(x[n].outputString()))
            {
            x[n].incRank();
            System.out.println(x[n].outputRank());
            u=1;
            break;
            }
            }
            
            if(u==0)
            {             
            x[i]=new sentence();
            x[i].inputString(line);
            x[i].incRank();
            System.out.println(x[i].outputRank());
            i++;           
            }
            
             
          
          
             }
             
           
}
         
  
    }
    
try
{    

int j,h,g;
    g = i;
    h = i;
    j = i;
int min=x[0].outputString().length();
int max=0;
int k=0;
for(k=0;k<i-1;k++)
    {
    if (x[k].outputRank() > max) 
        {
              max = x[k].outputRank();

        }
    }
System.out.print(max);
if(max==1)
{
for(k=1;k<j-1;k++)
    {
    if(min>x[k].outputString().length())
        min=x[k].outputString().length();
    }
for(k=0;k<h-1;k++)
    {
        if (min==x[k].outputString().length()) 
            {
                 answer.setText(x[k].outputString());

            }  
    }
}

else
    {    
    for(k=0;k<g-1;k++)
        {
            if (max==x[k].outputRank()) 
            {
                 answer.setText(x[k].outputString());
            }
        }  
    }
}

catch(Exception e)
    {

         answer.setText("Answer not found.");

    }

    PrintWriter pw = new PrintWriter("temp.txt");
    pw.close();



}


catch(FileNotFoundException e) 
{ 
    System.out.println("File not found");
}






     
    }//GEN-LAST:event_submitActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel answer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField question;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
